version: "3"
services:
  receiver:
    image: receiver
    deploy:
      replicas: 2
      restart_policy:
        delay: 10s
    ports:
      - "6060:8080"
    depends_on:
      - rabbitmq
  sender:
    image: sender
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
    ports:
      - "7070:8080"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.8.4-management
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"