version: "3"
services:
  receiver1:
    image: receiver
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
    ports:
      - "6060:8080"
    depends_on:
      - rabbitmq
    command: ["#"]
  receiver2:
    image: receiver
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
    ports:
      - "6070:8080"
    depends_on:
      - rabbitmq
    command: ["kern.*"]
  receiver3:
    image: receiver
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
    ports:
      - "6080:8080"
    depends_on:
      - rabbitmq
    command: ["*.critical"]
  receiver4:
    image: receiver
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
    ports:
      - "6090:8080"
    depends_on:
      - rabbitmq
    command: ["kern.*", "*.critical"]
  sender:
    image: sender
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
    ports:
      - "7070:8080"
    depends_on:
      - rabbitmq
    command: ["kern.critical", "A critical kernel error"]
  rabbitmq:
    image: rabbitmq:3.8.4-management
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"